sudo: false
language: python
cache: pip
python:
- 3.5
- 3.8
before_install:
- uname -a
- python --version
install:
- pip install -r requirements/travis.txt
script:
- tox -v
branches:
  only:
  - master
env:
- TOXENV=django22
- TOXENV=coverage
- TOXENV=quality
